export const SN_NET_SUITE = "netSuite"
export const NET_SUITE_INVENTORY_VARIANCES_UPDATED = "/INVENTORY_VARIANCES_UPDATED"
export const NET_SUITE_PRODUCT_STORE_SHIPMENT_METHODS_UPDATED = "/PRODUCT_STORE_SHIPMENT_METHODS_UPDATED"
export const NET_SUITE_PAYMENT_METHODS_UPDATED = "/PAYMENT_METHODS_UPDATED"