export const SN_KLAVIYO = "klaviyo";
export const KLAVIYO_UNIGATE_CONFIG_UPDATED = SN_KLAVIYO + "/UNIGATE_CONFIG_UPDATED";
export const KLAVIYO_CONNECTIONS_UPDATED = SN_KLAVIYO + "/CONNECTIONS_UPDATED";
export const KLAVIYO_CURRENT_UPDATED = SN_KLAVIYO + "/CURRENT_UPDATED";
export const KLAVIYO_CONFIGS_UPDATED = SN_KLAVIYO + "/CONFIGS_UPDATED";
export const KLAVIYO_EMAIL_SETTINGS_UPDATED = SN_KLAVIYO + "/EMAIL_SETTINGS_UPDATED";
export const KLAVIYO_FETCH_STATUS_UPDATED = SN_KLAVIYO + "/FETCH_STATUS_UPDATED";
export const KLAVIYO_CLEARED = SN_KLAVIYO + "/CLEARED";
