/**
 * App actions mapped to the server permissions they require.
 *
 * Views, components and routes should always refer to an action from this file instead of
 * hardcoding a server permission, so that a permission change is a one line change here.
 *
 * The value is the permission expression evaluated by `hasPermission` of the user store.
 * It supports the `OR` and `AND` operators, and an empty value means the action is allowed
 * for every logged in user.
 */
export default {
  APP_ORGANIZATIONS_VIEW: "PARTYMGR_VIEW OR PARTYMGR_ADMIN",
  APP_ORGANIZATION_UPDATE: "PARTYMGR_ADMIN",
  APP_USERS_VIEW: "USERS_LIST_VIEW OR PARTYMGR_VIEW OR PARTYMGR_ADMIN",
  APP_SECURITY_GROUPS_VIEW: "SECURITY_VIEW OR SECURITY_ADMIN",
  APP_SECURITY_CREATE: "SECURITY_CREATE OR SECURITY_ADMIN",
  APP_SECURITY_UPDATE: "SECURITY_UPDATE OR SECURITY_ADMIN",
  APP_SECURITY_GROUP_ASSIGN: "SECURITY_CREATE OR SECURITY_ADMIN OR PARTY_SECURITY_ASSIGNMENT",
  APP_APP_PERMISSIONS_VIEW: "APP_PERMISSION_VIEW OR APP_PERMISSION_CREATE OR APP_PERMISSION_UPDATE OR SECURITY_ADMIN",
  APP_APP_PERMISSION_CREATE: "APP_PERMISSION_CREATE OR SECURITY_ADMIN",
  APP_APP_PERMISSION_UPDATE: "APP_PERMISSION_UPDATE OR SECURITY_ADMIN",
  APP_PARTY_UPDATE: "PARTYMGR_UPDATE OR PARTYMGR_ADMIN",
  APP_PARTY_STATUS_UPDATE: "PARTYMGR_STS_UPDATE OR PARTYMGR_UPDATE OR PARTYMGR_ADMIN",
  APP_CONTACT_CREATE: "PARTYMGR_PCM_CREATE OR PARTYMGR_ADMIN",
  APP_CONTACT_UPDATE: "PARTYMGR_PCM_UPDATE OR PARTYMGR_UPDATE OR PARTYMGR_ADMIN",
  APP_CONTACT_DELETE: "PARTYMGR_PCM_DELETE OR PARTYMGR_ADMIN",
  APP_FACILITY_ASSIGNMENT_UPDATE: "STOREFULFILLMENT_ADMIN",
  APP_WEBTOOLS_VIEW: "WEBTOOLS_VIEW",
  APP_SHOPIFY_SYNC_ADMIN: "COMMON_ADMIN",
  APP_PWA_STANDALONE_ACCESS: "COMMON_ADMIN",
  APP_COMMERCE_VIEW: "COMMERCEUSER_VIEW"
} as const satisfies Record<string, string>
